on:
  release:
    types: [published]

jobs:
  release_web:
    runs-on: ubuntu-latest
    steps:
      - name: download HTML5
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          file: itch.io.zip
          token: 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

      - name: deploy to itch.io (HTML5)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: 8FrnKAFeno3XIWdTmeTn5rLAAb6qAzmcmthJIZhz
          CHANNEL: html
          ITCH_GAME: big-birb-run
          ITCH_USER: tanczmy
          PACKAGE: itch.io.zip
          VERSION: ${{ steps.download-html.outputs.version }}